# Generated by Django 3.1.5 on 2021-01-19 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policy',
            name='policy_quate_number',
        ),
        migrations.DeleteModel(
            name='Quate',
        ),
    ]
