# Generated by Django 3.1.5 on 2021-01-15 00:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210114_2345'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=255)),
                ('pet_species', models.PositiveSmallIntegerField(choices=[(0, 'Cat'), (1, 'Dog'), (2, 'Horse')], default=0)),
                ('pet_breed', models.PositiveSmallIntegerField(choices=[(0, 'Bulldog'), (1, 'Pug'), (2, 'Bocer')], default=0)),
                ('pet_age', models.PositiveIntegerField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
