# Generated by Django 3.1.5 on 2021-01-26 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_billingbot'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingbot',
            name='paid_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
