# Generated by Django 3.1.5 on 2021-01-26 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_billingbot_paid_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='paid_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
