# Generated by Django 3.1.5 on 2021-01-16 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210116_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address_1',
        ),
        migrations.RemoveField(
            model_name='user',
            name='address_2',
        ),
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='state',
        ),
    ]
