# Generated by Django 3.1.5 on 2021-01-17 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address_1',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='address_2',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default='', max_length=255),
        ),
    ]
