# Generated by Django 3.1.5 on 2021-01-17 20:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210117_2024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_premium', models.PositiveSmallIntegerField(choices=[(0, 'Silver'), (1, 'Gold'), (2, 'Platinum')], default=0)),
                ('policy_deductible', models.PositiveIntegerField()),
                ('policy_coinsurance', models.PositiveIntegerField()),
                ('policy_limit', models.PositiveIntegerField()),
                ('policy_discount', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
