# Generated by Django 3.1.5 on 2021-01-17 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='policy_number',
            field=models.CharField(default='12345', max_length=255),
        ),
    ]
