# Generated by Django 3.1.5 on 2021-01-17 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_policy_policy_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='policy_coinsurance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='policy',
            name='policy_deductible',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='policy',
            name='policy_limit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
