# Generated by Django 3.1.5 on 2021-01-17 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210117_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='pet_policy',
            field=models.ManyToManyField(to='core.Policy'),
        ),
    ]
