# Generated by Django 3.1.5 on 2021-01-18 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_pet_pet_policy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='pet_policy',
            new_name='pet_policy_premium',
        ),
    ]
