from model_utils import Choices


AGE_LIST = Choices(
    ('Dog', [
        '0-1 year',
        '1 year',
        '2 years',
        '3 years',
        '4 years',
        '5 years',
        '6 years',
        '7 years',
        '8 years',
        '9 years',
        '10 years',
        '11 years',
        '12 years',
        '13 years',
        '14 years',
        '15 years',
        '16 years',
        '17 years',
        '18 years',
        '19 years',
        '20 years or more',
    ]),
    ('Cat', [
        '0-1 year',
        '1 year',
        '2 years',
        '3 years',
        '4 years',
        '5 years',
        '6 years',
        '7 years',
        '8 years',
        '9 years',
        '10 years',
        '11 years',
        '12 years',
        '13 years',
        '14 years',
        '15 years',
        '16 years',
        '17 years',
        '18 years',
        '19 years',
        '20 years or more',
    ])
)
