from model_utils import Choices


BREED_LIST = Choices(
    ('Dog', [
        'Affenpinscher ',
        'Afghan Hound ',
        'Airedale Terrier ',
        'Akita ',
        'Alaskan Malamute ',
        'American Bandogge Mastiff ',
        'American Black and Tan Coonhound ',
        'American Bulldog ',
        'American English Coonhound ',
        'American Eskimo ',
        'American Foxhound ',
        'American Hairless Terrier ',
        'American Mastiff ',
        'American Pitbull Terrier ',
        'American Staffordshire Bull Terrier ',
        'American Staffordshire Terrier ',
        'American Water Spaniel ',
        'Anatolian Shepherd ',
        'Appenzeller Sennenhunde ',
        'Argentine Dogo ',
        'Australian Cattle Dog ',
        'Australian Kelpie ',
        'Australian Shepherd ',
        'Australian Silky Terrier ',
        'Australian Stumpy Tail Cattle ',
        'Australian Terrier ',
        'Azawakh Hound ',
        'Barbet ',
        'Basenji ',
        'Basset Fauve de Bretagne ',
        'Basset Hound ',
        'Bavarian Mountain Hound ',
        'Beagle ',
        'Bearded Collie ',
        'Beauceron ',
        'Bedlington Terrier ',
        'Belgian Mastiff ',
        'Belgian Sheepdog ',
        'Bergamasco Sheepdog ',
        'Berger Picard/Picardy Sheepdog ',
        'Bernese Mountain Dog ',
        'Bichon Frise ',
        'Black and Tan Coonhound ',
        'Black Russian Terrier ',
        'Blackmouth Cur ',
        'Bloodhound ',
        'Blue Picardy Spaniel ',
        'Blue Tick Coonhound ',
        'Boerboel ',
        'Bolognese ',
        'Border Collie ',
        'Border Terrier ',
        'Borzoi/Russian Wolfhound ',
        'Boston Terrier ',
        'Bouvier des Flandres ',
        'Boxer ',
        'Boykin Spaniel ',
        'Bracco Italiano ',
        'Briard ',
        'Brittany ',
        'Brussels Griffon ',
        'Bull Boxer ',
        'Bull Terrier ',
        'Bullmastiff ',
        'Cairn Terrier ',
        'Canaan Dog ',
        'Canadian Eskimo/Inuit ',
        'Cane Corso ',
        'Cardigan Welsh Corgi ',
        'Catahoula Leopard Dog ',
        'Caucasian Ovcharka ',
        'Cavalier King Charles Spaniel ',
        'Central Asian Shepherd ',
        'Cesky Terrier ',
        'Chesapeake Bay Retriever ',
        'Chihuahua ',
        'Chinese Crested ',
        'Chinook ',
        'Chipom ',
        'Chipoo ',
        'Chow Chow ',
        'Cirneco dell Etna ',
        'Clumber Spaniel ',
        'Cockapoo ',
        'Cocker Spaniel ',
        'Collie ',
        'Coonhound ',
        'Coton de Tulear ',
        'Curly-Coated Retriever ',
        'Czechoslovakian Wolfdog ',
        'Dachshund ',
        'Dalmatian ',
        'Dandie Dinmont Terrier ',
        'Deerhound ',
        'Dingo/Carolina ',
        'Doberman Pinscher ',
        'Dogue de Bordeaux ',
        'Drever ',
        'Dunker/Norwegian Hound ',
        'Dutch Sheepdog ',
        'English Bulldog ',
        'English Cocker Spaniel ',
        'English Foxhound ',
        'English Setter ',
        'English Shepherd ',
        'English Springer Spaniel ',
        'English Toy Spaniel ',
        'English Toy Terrier ',
        'Entlebucher Mountain Dog ',
        'Estrela Mountain Dog ',
        'Eurasian/Eurasier ',
        'Field Spaniel ',
        'Fila Brasileiro/Brazillian Mastiff ',
        'Finnish Lapphund ',
        'Finnish Spitz ',
        'Flat-Coated Retriever ',
        'Formosan (Taiwanese) Mountain Dog ',
        'Fox Terrier ',
        'French Bulldog ',
        'French Spaniel ',
        'Ganaraskan ',
        'Gascogne Braque Francais ',
        'German Pinscher ',
        'German Pointer ',
        'German Shepherd ',
        'German Spitz ',
        'German/Mittel Spitz ',
        'Giant Schnauzer ',
        'Glen of Imaal Terrier ',
        'Golden Retriever ',
        'Goldendoodle ',
        'Gordon Setter ',
        'Great Dane ',
        'Greater Swiss Mountain Dog ',
        'Greenland Dog ',
        'Greyhound ',
        'Groenendael Belgian Shepherd ',
        'Hamiltonstovare ',
        'Harrier ',
        'Havanese ',
        'Hovawart ',
        'Ibizan Hound ',
        'Icelandic sheepdog ',
        'Irish Setter ',
        'Irish Terrier ',
        'Irish Water Spaniel ',
        'Irish Wolfhound ',
        'Italian Bulldogge ',
        'Italian Greyhound ',
        'Jack Russell Terrier ',
        'Japanese Chin ',
        'Japanese Spitz ',
        'Japanese Terrier ',
        'Kai Ken ',
        'Karelian Bear Dog ',
        'Keeshond ',
        'Kerry Blue Terrier ',
        'Kishu Ken ',
        'Komondor ',
        'Kooikerhondje ',
        'Kuvasz ',
        'Labradoodle ',
        'Labrador Retriever ',
        'Laekenois Belgian Shepherd ',
        'Lagotto Romagnolo ',
        'Lakeland Terrier ',
        'Lancashire Heeler ',
        'Landseer ',
        'Large Munsterlander ',
        'Leonberger ',
        'Lhasa Apso ',
        'Lowchen ',
        'Malinois Belgian Shepherd ',
        'Maltese ',
        'Maltipoo ',
        'Manchester Terrier ',
        'Maremma ',
        'Mastiff ',
        'Mexican Hairless ',
        'Mi-Ki ',
        'Miniature Australian Shepherd ',
        'Miniature Bull Terrier ',
        'Miniature Dachshund ',
        'Miniature Pinscher ',
        'Miniature Poodle ',
        'Miniature Schnauzer ',
        'Mixed Breed - Dog - Unknown Size ',
        'Mudi ',
        'Neapolitan Mastiff ',
        'Newfoundland ',
        'Norfolk Terrier ',
        'Norrbottenspets ',
        'Norwegian Buhund ',
        'Norwegian Elkhound ',
        'Norwich Terrier ',
        'Nova Scotia Duck Tolling Retriever ',
        'Old Boston Bulldogge ',
        'Old English Sheepdog ',
        'Old Victorian Bulldogge ',
        'Olde English Bulldog ',
        'Otterhound ',
        'Papillon ',
        'Parson Russell Terrier ',
        'Patterdale/Fell Terrier ',
        'Pekingese ',
        'Pembroke Welsh Corgi ',
        'Perro de Presa Canario ',
        'Peruvian Inca Orchid ',
        'Petit Basset Griffon Vendeen ',
        'Pharaoh Hound ',
        'Picardy Spaniel ',
        'Plott ',
        'Pointer ',
        'Polish Lowland Sheepdog ',
        'Pomapoo ',
        'Pomeranian ',
        'Poodle ',
        'Porkie ',
        'Portuguese Podengo ',
        'Portuguese Pointer ',
        'Portuguese Water ',
        'Prague Ratter ',
        'Pudelpointer ',
        'Pug ',
        'Puggle ',
        'Puli ',
        'Pumi ',
        'Pyrenean Mastiff ',
        'Pyrenean Mountain Dog (Great Pyrenees) ',
        'Pyrenean Sheepdog ',
        'Pyrenean Shepherd ',
        'Pyrenees Braque Francais ',
        'Rafeiro do Alentejo ',
        'Rat Terrier ',
        'Redbone Coonhound ',
        'Rhodesian Ridgeback ',
        'Rottweiler ',
        'Russian Bolonka ',
        'Saint Bernard ',
        'Saluki (Gazelle Hound) ',
        'Samoyed ',
        'Schipperke ',
        'Schnoodle ',
        'Scottish Deerhound ',
        'Scottish Terrier ',
        'Sealyham Terrier ',
        'Segugio Italiano ',
        'Shar Pei ',
        'Shetland Sheepdog ',
        'Shiba Inu ',
        'Shih Tzu ',
        'Shikoku ',
        'Shiloh Shepherd ',
        'Siberian Husky ',
        'Silken Windhound ',
        'Silky Terrier ',
        'Skye Terrier ',
        'Sloughi ',
        'Small Munsterlander ',
        'Snoodle ',
        'Soft Coated Wheaten Terrier ',
        'Spanish Bulldog ',
        'Spanish Mastiff ',
        'Spanish Water Dog ',
        'Spinone Italiano ',
        'St. Johns Waterdog ',
        'Stabyhoun (Stabij) ',
        'Staffordshire Bull Terrier ',
        'Standard Schnauzer ',
        'Sussex Spaniel ',
        'Swedish Elkhound ',
        'Swedish Lapphund ',
        'Swedish Vallhund ',
        'Terrier ',
        'Terripoo ',
        'Tervuren Belgian Shepherd ',
        'Texas Blue Lacey ',
        'Thai Ridgeback ',
        'Tibetan Mastiff ',
        'Tibetan Spaniel ',
        'Tibetan Terrier ',
        'Tosa ',
        'Toy Fox Terrier ',
        'Toy Manchester Terrier ',
        'Toy Poodle ',
        'Treeing Walker Coonhound ',
        'Victorian Bulldog ',
        'Vizsla ',
        'Weimaraner ',
        'Welsh Sheepdog (Welsh Collie) ',
        'Welsh Springer Spaniel ',
        'Welsh Terrier ',
        'West Highland White Terrier ',
        'Whippet ',
        'Wirehaired Pointing Griffon ',
        'Yorkiepoo ',
        'Yorkshire Terrier ',
    ]),
    ('Cat', [
        'Abyssinian  ',
        'American Bobtail  ',
        'American Curl  ',
        'American Shorthair  ',
        'American Wirehair  ',
        'Anatolian  ',
        'Balinese  ',
        'Bengal  ',
        'Birman  ',
        'Bombay  ',
        'British Longhair  ',
        'British Shorthair  ',
        'Burmese  ',
        'California Spangled  ',
        'Chartreux  ',
        'Chausie  ',
        'Colorpoint Shorthair  ',
        'Cornish Rex  ',
        'Cymric  ',
        'Devon Rex  ',
        'Donskoy  ',
        'Egyptian Mau  ',
        'Exotic Longhair  ',
        'Exotic Shorthair  ',
        'Havana Brown  ',
        'Himalayan  ',
        'Japanese Bobtail  ',
        'Javanese  ',
        'Korat  ',
        'LaPerm  ',
        'Maine Coon  ',
        'Manx  ',
        'Mixed Breed - Cat  ',
        'Munchkin  ',
        'Nebelung  ',
        'Norwegian Forest  ',
        'Ocicat  ',
        'Oriental  ',
        'Persian  ',
        'Peterbald  ',
        'Pixiebob  ',
        'Ragdoll  ',
        'Russian Blue  ',
        'Savannah  ',
        'Scottish Fold  ',
        'Selkirk Rex  ',
        'Serengeti  ',
        'Siamese  ',
        'Siberian  ',
        'Singapura  ',
        'Snowshoe  ',
        'Somali  ',
        'Sphynx  ',
        'Thai  ',
        'Tiffany  ',
        'Tonkinese  ',
        'Toyger  ',
        'Turkish Angora  ',
        'Turkish Van  ',
        'Ojos Azules  ',
    ])
)
